/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaproject.utt.a22;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PionTest {
    @Test void appHasAGreeting() {
        
    }
}
